//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NorthwindModelContainer : DbContext
    {
        public NorthwindModelContainer()
            : base("name=NorthwindModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ADEM_DENEME()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADEM_DENEME");
        }
    
        public virtual int ADEM_PARSER(string p_TEXT)
        {
            var p_TEXTParameter = p_TEXT != null ?
                new ObjectParameter("P_TEXT", p_TEXT) :
                new ObjectParameter("P_TEXT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADEM_PARSER", p_TEXTParameter);
        }
    
        public virtual int CUSTOMER_ORDER_DETAILS(Nullable<decimal> p_ORDER_ID)
        {
            var p_ORDER_IDParameter = p_ORDER_ID.HasValue ?
                new ObjectParameter("P_ORDER_ID", p_ORDER_ID) :
                new ObjectParameter("P_ORDER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CUSTOMER_ORDER_DETAILS", p_ORDER_IDParameter);
        }
    
        public virtual int CUSTOMER_ORDER_HISTORY(string p_CUSTOMER_ID)
        {
            var p_CUSTOMER_IDParameter = p_CUSTOMER_ID != null ?
                new ObjectParameter("P_CUSTOMER_ID", p_CUSTOMER_ID) :
                new ObjectParameter("P_CUSTOMER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CUSTOMER_ORDER_HISTORY", p_CUSTOMER_IDParameter);
        }
    
        public virtual int CUSTOMER_ORDERS_ORDER(string p_CUSTOMER_ID)
        {
            var p_CUSTOMER_IDParameter = p_CUSTOMER_ID != null ?
                new ObjectParameter("P_CUSTOMER_ID", p_CUSTOMER_ID) :
                new ObjectParameter("P_CUSTOMER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CUSTOMER_ORDERS_ORDER", p_CUSTOMER_IDParameter);
        }
    
        public virtual int EMPLOYEE_SALES_BY_COUNTRY(Nullable<System.DateTime> p_BEGIN_DATE, Nullable<System.DateTime> p_END_DATE)
        {
            var p_BEGIN_DATEParameter = p_BEGIN_DATE.HasValue ?
                new ObjectParameter("P_BEGIN_DATE", p_BEGIN_DATE) :
                new ObjectParameter("P_BEGIN_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EMPLOYEE_SALES_BY_COUNTRY", p_BEGIN_DATEParameter, p_END_DATEParameter);
        }
    
        public virtual int FNC_FATURA(string p_SIPARIS_NO)
        {
            var p_SIPARIS_NOParameter = p_SIPARIS_NO != null ?
                new ObjectParameter("P_SIPARIS_NO", p_SIPARIS_NO) :
                new ObjectParameter("P_SIPARIS_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FNC_FATURA", p_SIPARIS_NOParameter);
        }
    
        public virtual int FNC_LOGIN_RETURN_USER(string p_USERNAME, string p_PASSWORD)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FNC_LOGIN_RETURN_USER", p_USERNAMEParameter, p_PASSWORDParameter);
        }
    
        public virtual int FNC_ORDERS_BETWEEN_DATE(string p_DATE1, string p_DATE2)
        {
            var p_DATE1Parameter = p_DATE1 != null ?
                new ObjectParameter("P_DATE1", p_DATE1) :
                new ObjectParameter("P_DATE1", typeof(string));
    
            var p_DATE2Parameter = p_DATE2 != null ?
                new ObjectParameter("P_DATE2", p_DATE2) :
                new ObjectParameter("P_DATE2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FNC_ORDERS_BETWEEN_DATE", p_DATE1Parameter, p_DATE2Parameter);
        }
    
        public virtual int FNC_USER_ORDERS(string p_USERID)
        {
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("P_USERID", p_USERID) :
                new ObjectParameter("P_USERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FNC_USER_ORDERS", p_USERIDParameter);
        }
    
        public virtual int GET_CUSTOMERS_TEST(string p_CUSTOMER_ID, string p_PARAM_TEST)
        {
            var p_CUSTOMER_IDParameter = p_CUSTOMER_ID != null ?
                new ObjectParameter("P_CUSTOMER_ID", p_CUSTOMER_ID) :
                new ObjectParameter("P_CUSTOMER_ID", typeof(string));
    
            var p_PARAM_TESTParameter = p_PARAM_TEST != null ?
                new ObjectParameter("P_PARAM_TEST", p_PARAM_TEST) :
                new ObjectParameter("P_PARAM_TEST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_CUSTOMERS_TEST", p_CUSTOMER_IDParameter, p_PARAM_TESTParameter);
        }
    }
}
